spring:
  application:
    name: Santander-dev-week
  datasource:
    url: jdbc:h2:mem:db_sdw
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enable: true